[pytest]
#testpaths = ['tests']
asyncio_mode = auto
; addopts = "--driver=Chrome"
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
pythonpath = src bindtools/src
main_file = src/bindmc/main.py